# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshm < Formula
  desc "A modern SSH connection manager for your terminal"
  homepage "https://github.com/Gu1llaum-3/sshm"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.10.0/sshm_Darwin_x86_64.tar.gz"
      sha256 "d77359968f26281520b6ed4f958e0fa4da302070b53506ea435a851b8a473f69"

      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.10.0/sshm_Darwin_arm64.tar.gz"
      sha256 "ea80736eb544feeae33a8ade254351636349279bb083caa2cae183bbe6c23175"

      def install
        bin.install "sshm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.10.0/sshm_Linux_x86_64.tar.gz"
      sha256 "86df71fa2618f8103c0e10206190e792ffc1954e371aaebb5a7870dab45bc5c9"
      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.10.0/sshm_Linux_armv6.tar.gz"
      sha256 "a71c0b7f02f3dcebcfdbbe9abc631cd5ab60f077865476590d5b8e5447b1f8c0"
      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.10.0/sshm_Linux_arm64.tar.gz"
      sha256 "a5e0559e344b8b99c3b57805c323e35e8df15c3b71f8aa03d4d65cb6956167ef"
      def install
        bin.install "sshm"
      end
    end
  end

  test do
    system "#{bin}/sshm --version"
  end
end
