# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshm < Formula
  desc "A modern SSH connection manager for your terminal"
  homepage "https://github.com/Gu1llaum-3/sshm"
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.9.0/sshm_Darwin_x86_64.tar.gz"
      sha256 "a31556bf3785ed616802809d1de2aa95e03404afc1a7790f757d345d57d87820"

      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.9.0/sshm_Darwin_arm64.tar.gz"
      sha256 "f24c7b780981005d7800737fb477934416df98ebb3b92c0671ac926e1df5f6d3"

      def install
        bin.install "sshm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.9.0/sshm_Linux_x86_64.tar.gz"
      sha256 "fc5817ec908e7d469bb6615fe9a53df6e2a81c26286d0311d40c967e218aed73"
      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.9.0/sshm_Linux_armv6.tar.gz"
      sha256 "8a7d08b00da7a0cfb02f7ce2f03e5154529b4249cb561051a4d1ce2fd196f544"
      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gu1llaum-3/sshm/releases/download/v1.9.0/sshm_Linux_arm64.tar.gz"
      sha256 "8399555f8d7da5e0574feb9c234f6a9a2d7e54177455ebfd9435f619e0776af2"
      def install
        bin.install "sshm"
      end
    end
  end

  test do
    system "#{bin}/sshm --version"
  end
end
